import type { Metadata } from 'next'
import { PrimeReactProvider } from 'primereact/api'
import 'primereact/resources/primereact.min.css'
import 'primereact/resources/themes/lara-dark-blue/theme.css'
import 'primereact/resources/themes/lara-light-blue/theme.css'
import 'primeicons/primeicons.css'
import 'primeflex/primeflex.css'
import 'primereact/resources/primereact.css'
import '../styles/layout.scss'
import { LayoutProvider } from '../layout/context/layoutcontext'
import Layout from '@/layout/layout'

export const metadata: Metadata = {
  title: 'Net Front',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="pt-BR">
      <head>
        <link id="theme-css" href={'/themes/lara-light-blue/theme.css'} rel="stylesheet"></link>
      </head>
      <body>
        <PrimeReactProvider>
          <LayoutProvider>
            <Layout>

              {children}
            </Layout>
          </LayoutProvider>
        </PrimeReactProvider>
      </body>
    </html>
  )
}
