import type { Metadata } from "next";

import { PrimeReactProvider } from 'primereact/api';

import "primereact/resources/primereact.min.css";
import "primereact/resources/themes/lara-light-green/theme.css";
import "primeicons/primeicons.css";

export const metadata: Metadata = {
  title: "Net Front",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PrimeReactProvider>
      <html lang="pt-BR" >
        <body>{children}</body>
      </html>
    </PrimeReactProvider>
  );
}
